msFilterList
: Expires=5
# abp_indo without element hiding 
# Last modified  Kamis 24 Maret 2011, 15:13:32 WIB
# Licence: http://indonesianadblockrules.googlecode.com/hg/subscriptions/COPYING
#
# Please report any unblocked adverts or problems
# via e-mail (hermawanadhis@gmail.com)
# http://indonesianfilter.blogspot.com
#
# *** abpindo_general_block.txt ***
- .com/iklan/
- .id/ads/
- .id/iklan/
- /admaxads.
- /iklan.
- /images/iklan/
- /uploads/iklan/
- http://banners-id.
# *** abpindo_adservers.txt ***
- http://1iklanbaris.com
- http://1jutarupiah.com
- http://1st-iklan.com
- http://abadiklan.com
- http://adbusinessfree.com
- http://adcenter2u.com
- http://addesigner.com
- http://adindonesia.com
- http://admarvel.com
- http://adptc.com
- http://adreviewcamp.com
- http://ads-iklan.net
- http://adsbingo.com
- http://adsenblogger.com
- http://adsense-id.com
- http://adsensemu.com
- http://adsentra.com
- http://adservingdaddy.com
- http://adspeedy.com
- http://adsrelease.com
- http://adv-adserver.com
- http://advercash.net
- http://advertspeed.com
- http://agenpromosi.com
- http://ajangiklangratis.com
- http://alamatemail.com
- http://anadvertorial.com
- http://anekaiklan.com
- http://antariklan.com
- http://arisanvip.com
- http://axverta.com
- http://ayoburuanklik.com
- http://baliadv.com
- http://bannerbux.com
- http://barisiklangratis.com
- http://bebaspikiran.com
- http://bekas.com
- http://belajar-bisnis.com
- http://bigextracash.com
- http://biindit.com
- http://bincangbisnis.com
- http://biroiklangratis.com
- http://biropromosi.com
- http://blogiklanbaris.com
- http://bubuads.com
- http://buildvertical.com
- http://bursapromo.com
- http://buyiads.com
- http://carasukses.com
- http://cash-harvest.com
- http://cashviews.com
- http://clickdbs.com
- http://clicklifter.com
- http://clickmedia.co.id
- http://clicks4cents.com
- http://clicksia.com
- http://clickxchange.com
- http://cyberpromo.biz
- http://daniklan.com
- http://dbclix.com
- http://desaiklan.com
- http://dewa-bisnis.com
- http://direktori-iklan.com
- http://disinigratis.com
- http://doubleclick.com
- http://drumcash.com
- http://duitmu.com
- http://duniaiklangratis.com
- http://dutawebiklan.com
- http://earneasycash.info
- http://easyad.us
- http://entryad.com
- http://flexterkita.com
- http://forexpose.com
- http://forum-iklan.com
- http://forumiklan.com
- http://freeads-iklan.com
- http://freeads.web.id
- http://gadget-ads.com
- http://gratis-iklan-baris.com
- http://gratisiklanpasang.com
- http://gratisiklanpasang.net
- http://gratispromo.com
- http://groupiklan.com
- http://hiddenbux.com
- http://iaiamedia.com
- http://idr-clickit.com
- http://iklan-baris.org
- http://iklan-global.com
- http://iklan-iklan.com
-d iklan-jaya.com /images/
- http://iklan-laris.com
- http://iklan-sukses.com
- http://iklan-super.com
- http://iklan.net
- http://iklan.terpopuler.com
- http://iklan.tipsntrik.com
- http://iklan2009.com
- http://iklanad.com
- http://iklanads.com
- http://iklanasional.com
- http://iklanbaliku.com
- http://iklanbaris-gratis.com
- http://iklanbaris.biz
- http://iklanbaris.co.id
- http://iklanbaris.im
- http://iklanbaris.ws
- http://iklanbarisaceh.com
- http://iklanbarisgratis.co.uk
- http://iklanbarisgratis.info
- http://iklanbarisgratis.net
- http://iklanbarisgratis.org
- http://iklanbarisgratispasang.com
- http://iklanbarisgratispasang.net
- http://iklanbariskusuma.com
- http://iklanbarislaris.com
- http://iklanbarismandiri.com
- http://iklanbarismu.com
- http://iklanbarisplus.com
- http://iklanbarispro.com
- http://iklanbaristanpadaftar.com
- http://iklanbaru.com
- http://iklanbiru.com
- http://iklanbisnis.net
- http://iklanbisnisbali.com
- http://iklanbisnisindonesia.com
- http://iklanbisnisku.com
- http://iklanbisnispro.com
- http://iklanbogor.com
- http://iklandb.com
- http://iklandenpasar.com
- http://iklandiweb.com
- http://iklandunia.com
- http://iklanebook.com
- http://iklanekstra.com
- http://iklaner.com
- http://iklanfun.com
- http://iklangoogle.com
- http://iklangra-tis.com
- http://iklangratis.co.uk
- http://iklangratis.info
- http://iklangratis.us
- http://iklangratis88.com
- http://iklangratisindonesia.com
- http://iklangratisindonesia.net
- http://iklangratisindonesia.org
- http://iklangratiskita.com
- http://iklangratiskusuma.com
- http://iklangratismu.com
- http://iklangratisonline.com
- http://iklangratispasang.biz
- http://iklangratispasang.com
- http://iklangratispasang.net
- http://iklangratispasang.org
- http://iklangratispro.com
- http://iklanhemat.com
- http://iklanhoki.com
- http://iklanhouse.com
- http://iklanjago.com
- http://iklanjagoan.com
- http://iklanjoglo.com
- http://iklanjualbeli.info
- http://iklankami.com
- http://iklankito.com
- http://iklankomplit.com
- http://iklanku.info
- http://iklanlaku.com
- http://iklanlisting.com
- http://iklanlowongan.com
- http://iklanmarket.com
- http://iklanmini.co.id
- http://iklanmobil.org
- http://iklanmotor.org
- http://iklanoke.com
- http://iklanonlinegratis.com
- http://iklanonlinemu.com
- http://iklanpartai.com
- http://iklanpasanggratis.com
- http://iklanpedia.com
- http://iklanperklik.com
- http://iklanplaza.com
- http://iklanposkota.net
- http://iklanpremium.com
- http://iklanprima.com
- http://iklanprima.info
- http://iklanprimaku.com
- http://iklanprime.com
- http://iklanpromo.com
- http://iklanshop.com
- http://iklansilver.com
- http://iklantanpadaftar.com
- http://iklanteks.com
- http://iklantelevisi.com
- http://iklanterpopuler.com
- http://iklantext.com
- http://iklantop.net
- http://iklanumum.com
- http://iklanvip.net
- http://iklanvoucher.com
- http://iklanwebid.com
- http://iklanyahoo.com
- http://incentria.com
- http://incrasebux.com
- http://indo-solusta.com
- http://indoadpro.com
- http://indobanner.com
- http://indobuysell.com
- http://indofad.com
- http://indofreeads.com
- http://indoglobe.com
- http://indonesiaptc.com
- http://indoptc.com
- http://indostats.com
- http://indovertiser.com
- http://infinityads.com
- http://inmobi.com
- http://innity.net
- http://istanaiklan.com
- http://jagoiklan.com
- http://jagopromo.com
- http://jaringaniklan.com
- http://jasaiklan.com
- http://javaiklan.com
- http://jillsclickcorner.com
- http://jingkrak.com
- http://jituiklan.com
- http://jurnaliklan.com
- http://juruiklan.com
- http://ketikiklan.com
- http://kiosiklanbaris.com
- http://kiospromo.com
- http://klik11.com
- http://klikabadi.com
- http://klikabadi.net
- http://klikajadeh.com
- http://klikptc.com
- http://klikrupiah.com
- http://kliksaya.com
- http://kolamiklan.com
- http://komisiiklan.com
- http://kumpulblogger.com
- http://kumpulnet.com
- http://ladangiklan.com
- http://ladanguang.com
- http://lokeriklan.com
- http://malaysianad.com
- http://maripromosi.com
- http://masteriklan.net
- http://mauiklangratis.com
- http://medaniklan.com
- http://media-gratis.com
- http://mediaiklan.info
- http://mediaiklanpapua.com
- http://mediapromosi.co.id
- http://mediapromosi.web.id
- http://medyaklik.com
- http://mesiniklan.andipublisher.com
- http://mesinuangku.com
- http://metodebaru.com
- http://modaliklan.com
- http://motoriklan.com
- http://mpnrs.com
- http://mybannermaker.com
- http://negeriads.com
- http://neobux.com
- http://neorupiah.com
- http://nspmotion.com
- http://nuansaiklan.com
- http://okepromo.com
- http://omnibux.com
- http://onbux.com
- http://onclinic24.com
- http://onedollarptc.com
- http://paid-to-promote.net
- http://paidforfree.com
- http://paidtoclick.com
- http://paneniklan.com
- http://papan-iklan.com
- http://pasang-iklan.com
- http://pasang-iklanbaris.com
- http://pasang-iklangratis.com
- http://pasanggratisiklan.com
- http://pasangiklan.com
- http://pasangiklanbaris.com
- http://pasangiklanbaris.net
- http://pasangiklanbarisgratis.com
- http://pasangiklanbarisgratis.net
- http://pasangiklanbarisgratis.org
- http://pasangiklangratis.com
- http://pasangiklangratis.org
- http://pasangiklangratisbaris.com
- http://pasangiklangratisbaris.net
- http://pasangiklanku.com
- http://pasangiklanmu.com
- http://pasarbaris.com
- http://pasariklanbaris.com
- http://paypalbisnis.com
- http://paypopup.com
-d plazalowongan.com /bnr/
- http://pondokiklan.com
- http://popupmoney.com
- http://portaliklan.com
- http://ppcinbox.com
- http://ppcindo.com
- http://ppcindonesia.net
- http://ppcklik.com
- http://profiadvert.com
- http://promobagus.com
- http://promobebas.com
- http://promobersama.com
- http://promocionesweb.com
- http://promoiklanbarisgratis.com
- http://promojunkie.com
- http://promoku.com
- http://promoneysystem.com
- http://promosiiklan.com
- http://propertitop.com
- http://pundibux.net
- http://pusatiklan.com
- http://pusatmarketing.com
- http://pusatpromosiiklan.com
- http://rahasiapanas.com
- http://ratubola.com
- http://referral-secrets.com
- http://revenueburner.com
- http://ruangbisnis.com
- http://rupiahbux.com
- http://salesgratis.com
- http://sanglah.com
- http://scarlet-clicks.info
- http://sebar.idblognetwork.com
- http://sentra-iklan.com
- http://sentrapromosi.com
- http://serbaiklan.com
- http://serbapromo.com
- http://sexiklan.com
- http://sharepointads.com
- http://shbux.com
- http://siapakaya.com
- http://situsiklan.web.id
- http://situsiklanbaris.com
- http://skycpm.com
- http://smart-iklan.com
- http://sogoplaza.com
- http://spotiklan.net
- http://spyonad.com
- http://sukagratis.com
- http://sumberiklan.com
- http://supbux.com
- http://super-iklan.com
- http://superiklantop.com
- http://surgapromo.com
- http://suryabanner.com
- http://suryaiklan.com
- http://tagiklan.com
- http://tekbux.com
- http://teknikbisnis.com
- http://teliad.com
- http://tempatiklan.com
- http://texasptc.com
- http://textlinksdepot.com
- http://textspace.net
- http://the-freeads.com
- http://theclickers.net
- http://tinggalklik.com
- http://tipsiklan.com
- http://tokobagus.com
- http://topklik.com
- http://trekpay.com
- http://trendiklan.com
- http://triklan.com
- http://uangklik.com
- http://unobux.com
- http://updateiklan.com
- http://valueclick.net
- http://vistaclix.com
- http://webiklan.com
- http://weblogiklan.com
- http://yesads.com
- http://zonaiklan.info
# *** abpindo_specific_block.txt ***
-d 21cineplex.com /data/videoad/
# ||adf.ly/js/link-converter.js$domain=indowebster.web.id
# ||ads.indowebster.com^$script,image,subdocument
# ||ads.kompas.com^$script,image,subdocument
# ||arenabola.com^$domain=krucil.com
# ||asiafriendfinder.com^$domain=indowebster.com|maknyos.com
-d cashburners.biz /banners/
-d cdn.bloggerfiles.com /img/promo/
-d ceriwis.info /338x30.swf
-d ceriwis.us /338x30.swf
-d chip.co.id /microsite/frame/index.html
-d cloudfront.net /bisnis/images/banners/
-d detiknews.com /iklanbaris/
-d dewamabuk.com /images/banner/
-d ebsoft.web.id /wp-content/banners/
-d endonesia.com /banner1/dbc-kantorku.jpg
-d endonesia.com /en1.gif
-d endonesia.com /images/banner-rodadua-net.gif
-d endonesia.com /images/modis-shop.gif
-d endonesia.com /images/officialweb.gif
-d freewebs.com /peluang-bisnis/kaya23.gif
-d gudeg.net /images/banner/
-d harianjogja.com /img/Bnr/
-d howsanindo.com /website/bisnisparfum/bisnisparfum_dijual.gif
-d idblognetwork.com /images/banner468x60/
-d idblognetwork.com /images/banner728x90/
# ||image.bloggerfiles.com/img/promo/$domain=gudanglagu.com
-d imagedum.com /images/457_Arenabola.png
-d imagedum.com /images/774_Tangkasbet.gif
-d imagedum.com /images/928_Ratubola.gif
-d img5.uploadhouse.com /fileuploads/7341/734124591c261b70951dfd979b37074530dcd6b.jpg
-d img5.uploadhouse.com /fileuploads/7341/7341275e70e126e6020b7970749f1517cddfa57.jpg
-d img6.uploadhouse.com /fileuploads/6946/6946586ec80b6e1318c82b46fe31274e46bae48.jpg
-d img7.uploadhouse.com /fileuploads/6944/69444773bf87af9d201f0bf2f81c7c083529805.jpg
-d indobokepz.com /images/banner-slideshow.jpg
-d indomp3z.us /banner/banner.fileserve.gif
-d indomp3z.us /images/ITZ-launch.jpg
-d indomp3z.us /images/fileserverpromote.gif
-d indomp3z.us /images/hotfile.jpg
-d indomp3z.us /images/imzupload.gif
-d indonesiapaypal.com /banners/flash/Banner250x250.swf
# ||indowebster.com/ajax/iklan/$xmlhttprequest
-d javapic.com /ikelan/
# ||javapic.com/images/*.gif$domain=krucil.com
-d jogjastreamers.com /images/banner/
-d kad.kaskus.us /banner/
-d kaskus.us /adv/
-d kaskus.us /banner/Kas_In-House-Banner_120x240_alt-2.jpg
-d ketawa.com /img-iklan/
-d kikil.org /ads3.php
-d kikil.org /adsbahenol.html
-d kikil.org /network/uploaded_banners/
-d kompas.com /data/banner/
-d koranlokal.com /iklan_baru/
-d koranlokal.com /newstickerpartai.php
-d koranlokal.com /point1.php
-d krucil.com /bb17-iklan.php
-d lintasberita.com /public/images/bannermidlecenter.jpg
-d liquidweb.com /banners/
-d lytogame.com /images/partner/
-d lytogame.com /partner/
-d mediaindonesia.com /public/banner/flash/
-d megindo.net /megindo2/data/affiliates/
-d megindo.net /megindo2/images/banner-
-d modemku.com /image-banner/
-d modifikasi.com /images/banner/close.gif
-d modifikasi.com /images/banner_
-d musisi.com /musifile/images_banner/
-d oprekpc.com /banner/
-d perawan.us /images/banner/
-d poems.web.id /poemspromo/
-d primbon.com /banner/
-d readbud.com /images/125_125_banner.jpg
-d resep.web.id /banner/
-d stafaband.info /tb.swf
-d static.escavern.com /tokomaya.gif
-d suarabola.com /banners/
-d suaramedia.com /images/banners/
# ||swfcabin.com^$domain=krucil.com
# ||tinypic.com^*.gif$domain=bluefame.com|indobokepz.com|kikil.org|krucil.com|masterporn.me|perawan.us
-d tribunnews.com //iklan/
-d uki.ac.id /images/samkokbet.swf
# ||uploadhouse.com^*.gif$domain=krucil.com
# ||us.openx.detik.com^$~third-party
-d videogamesindonesia.com /banners/
-d vivanews.com /appaux/ads/
# *** abpindo_whitelist.txt ***
