msFilterList
: Expires=5
# JBet - filter untuk menghindari Jebakan Betmen
# Last modified 14 April 2014, 22:51:40 WIB
# Homepage: http://abpindo.blogspot.com/
# Licence: http://indonesianadblockrules.googlecode.com/hg/subscriptions/COPYING
#
# Please report any unblocked adverts or problems
# in the forums (http://forums.lanik.us/viewforum.php?f=94)
#
# *** abpindo_computer_prank.txt ***
- http://1227.com
- http://1priest1nun.com
- http://2girls1finger.com
- http://2guys1hole.com
- http://2guys1horse.com
- http://4girlsfingerpaint.com
- http://asianthumbx.com
-d bangun3.com /admin
- http://bluewaffle.com
- http://bmepainolympics2.com
- http://boi.netai.net
- http://bottleguy.com
- http://bouncecup.com
- http://bowlgirl.com
- http://charonboat.com
- http://cherrycake.org
- http://clownsong.com
- http://coryna.com
- http://cupchicks.com
-d d1gdo.com /admin/
-d d1gdo.com /images
- http://dadparty.com
- http://denial.be
- http://drewpickles.com
- http://eatingcream.com
- http://eelsoup.net
- http://fanbangho.com
- http://festered.com
- http://fingerslam.com
- http://fishermen.ytmnd.com
- http://fragskin.com
- http://fruitlauncher.com
- http://funnelchair.com
- http://ghostboy.co.uk
- http://ginedis.com
- http://gncr.org
- http://goatse.cz
- http://goatsegirl.org
- http://goatsemarathon.com
- http://googlehammer.com
- http://gooork.com
- http://goplaysee.com
- http://goregasm.com
- http://grubbychicks.com
- http://gurochan.net
- http://hai2u.com
- http://hdvideoforums.org
- http://hihanin.com
- http://homewares.org
- http://homo.com
- http://hurr-durr.com
- http://infoslash.net
- http://japscat.org
- http://joyangeles.com
- http://k-k-k.com
- http://kids-in-sandbox.com
- http://killerijo.net
- http://kingfamilyphotoalbum.com
- http://landslide.nu
- http://lemonparty.org
- http://likaraoke.com
- http://lolhello.com
- http://lolshock.com
- http://loltrain.com
- http://macory.com
- http://magic4you.nu
- http://mangems.com
- http://martectx.de
- http://meatrolled.com
- http://meatspin.com
- http://melondude.com
-d members.home.nl /saen/special/zoeken.swf
- http://milkfountain.com
- http://moldymen.com
- http://motherman.com
- http://mrshands.com
- http://mudfall.com
- http://mudmonster.org
- http://niggers.on.nimp.org
- http://nobrain.dk
- http://nutabuse.com
- http://nutsindaass.com
- http://octopusgirl.com
- http://ogrish.com
- http://phonejapan.com
- http://phonetrace.org
- http://podrido.com
- http://poobutton.com
- http://porkspin.com
- http://pressurespot.com
- http://prolapseman.com
- http://purplehoodie.com
- http://qsng.cn
-d rumdesign.com /wrong/
- http://sajjadali.com
- http://seksburada.net
- http://shitpassion.com
-d sinthaistudio.com /thehouse2/
- http://sportsmansclub.net
- http://stock888.cn
- http://subang.co.tv
- http://subangtv.co.tv
- http://suckdude.com
- http://sukatoro.com
- http://sweety.biz
- http://swollentip.com
- http://teamclouds.com
- http://texaswhitetailfever.com
- http://thatsnotsexy.com
- http://themacuser.org
- http://themobiletracker.com
- http://thepounder.com
- http://theshithole.com
- http://thewillpower.org
- http://turdgasm.com
- http://vomitgirl.org
- http://walkthedinosaur.com
- http://whoomp.org
- http://winterrowd.com
- http://wormgush.com
- http://wowomg.com
- http://xnescat.info
- http://yellaface.com
- http://youaresogay.com
