msFilterList
: Expires=5
# JBet - filter untuk menghindari Jebakan Betmen
# Last modified 10 August 2013, 19:06:17 WIB
# Homepage: http://abpindo.blogspot.com/
# Licence: http://indonesianadblockrules.googlecode.com/hg/subscriptions/COPYING
#
# Please report any unblocked adverts or problems
# via e-mail (hermawanadhis@gmail.com)
# in the forums (http://forums.lanik.us/viewforum.php?f=94)
#
# *** _computer_prank.txt ***
- http://1227.com
- http://1guy1mudpie.com
- http://1priest1nun.com
- http://2girls1finger.com
- http://2girls1fleshlight.com
- http://2girls1kracker.com
- http://2guys1hole.com
- http://2guys1horse.com
- http://4girls1mouth.com
- http://4girlsfingerpaint.com
- http://aladel.net
- http://apaaaantuh.co.cc
- http://asianthumbx.com
- http://bagslap.com
-d bangun3.com /admin
- http://biblecamp.info
- http://blink-182.com
- http://bluewaffle.com
- http://bmepainolympics2.com
- http://boi.netai.net
- http://bokre.com
- http://bottleguy.com
- http://bouncecup.com
- http://bowlgirl.com
- http://charonboat.com
- http://cherrycake.org
- http://clownsong.com
- http://coryna.com
- http://cupchicks.com
-d d1gdo.com /admin/
-d d1gdo.com /images
- http://dadparty.com
- http://denial.be
- http://dfwdiesel.net
- http://divineenterprises.net
- http://drewpickles.com
- http://eatingcream.com
- http://eelsoup.net
- http://epustakawan.co.cc
-d esc-creation.com /scream
- http://fadebook.com
- http://fanbangho.com
- http://festered.com
- http://fingerslam.com
- http://fishermen.ytmnd.com
- http://fragskin.com
- http://fruitlauncher.com
- http://fudgepipe.com
- http://funnelchair.com
- http://gandhi.isgreat.org
- http://geryadrian.com
- http://ghostboy.co.uk
-d gigihweb.com /unik
- http://ginedis.com
- http://gncr.org
- http://goatse.cz
- http://goatsegirl.org
- http://goatsemarathon.com
- http://googlehammer.com
- http://gooork.com
- http://goplaysee.com
- http://goregasm.com
- http://grubbychicks.com
- http://gurochan.net
- http://hai2u.com
- http://hdvideoforums.org
- http://hihanin.com
- http://homewares.org
- http://homo.com
- http://hurr-durr.com
- http://infoslash.net
- http://japscat.org
- http://jewdiamonds.com
- http://jewsnip.com
- http://joyangeles.com
- http://k-k-k.com
- http://kids-in-sandbox.com
- http://killerijo.com
- http://killerijo.net
- http://killerjo.net
- http://kingfamilyphotoalbum.com
- http://kombre.co.cc
- http://krnacjalneg.info
- http://l33thaxor.tk
- http://landslide.nu
- http://lemonparty.org
- http://likaraoke.com
- http://lolhello.com
- http://lolshock.com
- http://loltrain.com
- http://macory.com
- http://mactep.org
- http://magic4you.nu
- http://mangems.com
- http://marbling.pe
- http://martectx.de
- http://meatrolled.com
- http://meatspin.com
- http://melondude.com
-d members.home.nl /saen/special/zoeken.swf
- http://milkfountain.com
- http://moldymen.com
- http://motherman.com
- http://mrshands.com
- http://mudfall.com
- http://mudmonster.org
- http://niggers.on.nimp.org
- http://nobrain.dk
- http://nutabuse.com
- http://nutgobbler.com
- http://nutsindaass.com
- http://octopusgirl.com
- http://ogrish.com
- http://oranggila.com
- http://ouchmyeyes.com
- http://out.ihang.org
- http://phonejapan.com
- http://phonetrace.org
- http://podrido.com
- http://poobutton.com
- http://porkspin.com
- http://pressurespot.com
- http://prolapseman.com
- http://pronline.ru
- http://purplehoodie.com
- http://qsng.cn
- http://ratemyshocker.com
- http://reinaldi.com
-d rumdesign.com /wrong/
- http://sajjadali.com
- http://seksburada.net
- http://shitpassion.com
-d sinthaistudio.com /thehouse2/
- http://sourpatch.org
- http://sportsmansclub.net
- http://stagparty.us
- http://stainedass.com
- http://stock888.cn
-d stuff.pyzam.com /toys/tictacscare.swf
- http://subang.co.tv
- http://subangtv.co.tv
- http://suckdude.com
- http://sukatoro.com
- http://sweety.biz
- http://swollentip.com
- http://tathli.com
- http://teamclouds.com
- http://texaswhitetailfever.com
- http://thatsnotsexy.com
- http://themacuser.org
- http://themobiletracker.com
- http://thepounder.com
- http://theshithole.com
- http://thewillpower.org
- http://turdgasm.com
- http://ugly.blerp.org
- http://vomitgirl.org
- http://wadefamilytree.org
- http://walkthedinosaur.com
- http://watchmcrankdat.com
- http://whipkrack.org
- http://whoomp.org
- http://winterrowd.com
- http://workse.cx
- http://wormgush.com
- http://wowomg.com
- http://xnescat.info
- http://yellaface.com
- http://youaresogay.com
