# This workflow will install Python dependencies
name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        python tools/FOP.py
    - name: python-abp
      run: |
        pip install --upgrade python-abp
    - name: render
      run: |
        flrender -i abpindo=. abpindo.template subscriptions/abpindo.txt
        flrender -i abpindo=. abpindo_hosts.template subscriptions/abpindo_hosts.txt
        flrender -i abpindo=. abpindo_hosts_annoyance.template subscriptions/abpindo_hosts_annoyance.txt
        flrender -i abpindo=. abpindo_noannoyance.template subscriptions/abpindo_noannoyance.txt
        flrender -i abpindo=. abpindo_noelemhide.template subscriptions/abpindo_noelemhide.txt
