name: autobuild

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install python-abp
      run: |
        python -m pip install --upgrade pip
        pip install python-abp
    - name: Build
      run: |
        # Ensure output directory exists
        mkdir -p $GITHUB_WORKSPACE/subscriptions
        # Run FOP.py to sort src/ directory
        python $GITHUB_WORKSPACE/tools/FOP.py
        # flrender commands for abpindo filters
        flrender -i abpindo=. $GITHUB_WORKSPACE/abpindo.template $GITHUB_WORKSPACE/subscriptions/abpindo.txt
        flrender -i abpindo=. $GITHUB_WORKSPACE/abpindo_extended.template $GITHUB_WORKSPACE/subscriptions/abpindo_extended.txt
        flrender -i abpindo=. $GITHUB_WORKSPACE/abpindo_annoyances.template $GITHUB_WORKSPACE/subscriptions/abpindo_annoyances.txt
        flrender -i abpindo=. $GITHUB_WORKSPACE/abpindo_hosts.template $GITHUB_WORKSPACE/subscriptions/abpindo_hosts.txt
        flrender -i abpindo=. $GITHUB_WORKSPACE/abpindo_hosts_adult.template $GITHUB_WORKSPACE/subscriptions/abpindo_hosts_adult.txt
        flrender -i abpindo=. $GITHUB_WORKSPACE/abpindo_noadult.template $GITHUB_WORKSPACE/subscriptions/abpindo_noadult.txt
        flrender -i abpindo=. $GITHUB_WORKSPACE/abpindo_noelemhide.template $GITHUB_WORKSPACE/subscriptions/abpindo_noelemhide.txt
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Auto-Build abpindo filters"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
