name: CI Build

on:
  push:  # Memicu workflow saat ada perubahan (push) ke repositori
    branches:
      - main  # Ganti dengan nama cabang yang sesuai jika perlu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ganti dengan versi Python yang sesuai

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-abp adblock-decoder  # Menginstal paket yang diperlukan

      - name: Run build.sh
        run: |
          chmod +x build.sh  # Memberikan izin eksekusi
          ./build.sh         # Menjalankan skrip
